name: CI Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run checks
              run: pnpm run lint
